[general]
working_directory = "C:\\Users\\Sergio.Lopes\\home\\"
[font]
normal = { family = "CommitMono Nerd Font Mono" }
size = 12.25

[terminal]
shell = { program = "C:\\Users\\Sergio.Lopes\\AppData\\Local\\Programs\\Git\\bin\\bash.exe"}

[env]
NODE_TLS_REJECT_UNAUTHORIZED = "0"
